version: "3"
services:
  adonis-api:
    build:
      context: ./adonis-api
    ports:
      - "3333:3333"
    volumes:
      - ./adonis-api:/app
    env_file:
      - ./.env

  # flask-ai:
  #   build: ./flask-ai
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./flask-ai:/app
  #   environment:
  #     - FLASK_ENV=development

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  postgres_data:
