version: "3"
services:
  adonis-api-dev:
    build:
      context: ./adonis-api
      target: dev
    ports:
      - "3333:3333"
    volumes:
      - ./adonis-api:/app
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

  # adonis-api-prod:
  #   build:
  #     context: ./adonis-api
  #     target: prod
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - ./.env

  # flask-ai:
  #   build: ./flask-ai
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./flask-ai:/app
  #   environment:
  #     - FLASK_ENV=development

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
